### PR TITLE
allow ws proxying in nginx

### PR DESCRIPTION
**Pull request by ruslandoga**
Relevant:
- https://github.com/plausible/analytics/discussions/3826
- https://github.com/plausible/analytics/discussions/3817#discussioncomment-8615006

### CODE REVIEW

**Comment by kurdin** [comment]
@ruslandoga 
I added few more options to make it better reverse proxy
https://github.com/plausible/community-edition/pull/119

**Review by kurdin — APPROVED** [review]

**Comment by ruslandoga** [comment]
@kurdin thank you!

**Comment by dimejo** [comment]
@ruslandoga
I just noticed that this PR has not been merged into v2.1.0. Was that intended?

**Comment by ruslandoga** [comment]
@dimejo thank you for noticing. No, I should've rebased v2.1.0 against v2.0.0 after merging it. I'll do it now.

**Pull request merged**
