### PR TITLE
Add health check to docker compose

### PR DESCRIPTION
**Pull request by willnode**
Added a health check so the service can heal from crashing by itself.

### CODE REVIEW

**Comment by ruslandoga** [comment]
👋 @willnode 

How does it compare to https://github.com/plausible/community-edition/pull/83? I'm afraid that setup would make the startup too slow (>30 seconds)

**Comment by willnode** [comment]
The healthcheck for the clickhouse is [the recommended way](https://stackoverflow.com/a/73326197/3908409) of doing health check. Wait I'll benchmark it on my live server.

**Comment by ruslandoga** [comment]
> The healthcheck for the clickhouse is [the recommended way](https://stackoverflow.com/a/73326197/3908409) of doing health check.

Seems to be just a (possibly outdated) StackOverflow answer. Is there any official source recommending this exact approach? I'd think `clickhouse client` would be recommended now.

**Comment by willnode** [comment]
>  I'm afraid that setup would make the startup too slow (>30 seconds)

I can add these parameters (if you OK with fairly new docker compose requirement to `2.20` if i'm not mistaken)

```
    healthcheck:
      test: ...
      start_interval: 2s
      start_period: 1m
```
The startup from last `down` is like this now:
```
$ time docker compose up -d --wait
[+] Running 4/4
 ✔ Network public_html_default                  Created            0.1s
 ✔ Container public_html-plausible_db-1         Healthy            3.7s
 ✔ Container public_html-plausible_events_db-1  Healthy            3.7s
 ✔ Container public_html-plausible-1            Healthy           22.2s

real    0m22.428s
user    0m0.149s
sys     0m0.089s
```

If `--wait` omitted the startup would only need 3.7s

> Is there any official source recommending this exact approach?

https://clickhouse.com/docs/en/interfaces/http

> In health-check scripts use GET /ping request. 

But both works and I see no difference in timing anyway.

**Comment by ruslandoga** [comment]
> I can add these parameters

Yes, please do :)

**Comment by willnode** [comment]
Added

**Comment by ruslandoga** [comment]
👋 @willnode 

I tried it on my instance for the last week, and all was great. Thank you!

**Comment by ruslandoga** [comment]
👋 @willnode 

Sorry to bother you, but it seems like pg_isready is using root user, can you please verify? Should we edit the healthcheck to use `$PG_USER` or whatever it is? Or should we express the command as a list `["CMD", "pg_isready"]`, I remember there were some differences between that expression and a string which uses the shell, and possibly that's where the root user is coming from.

```
...
plausible_db-1  | 2024-08-02 10:35:25.439 UTC [575826] FATAL:  role "root" does not exist
plausible_db-1  | 2024-08-02 10:35:55.557 UTC [575835] FATAL:  role "root" does not exist
plausible_db-1  | 2024-08-02 10:36:25.681 UTC [575841] FATAL:  role "root" does not exist
plausible_db-1  | 2024-08-02 10:36:55.798 UTC [575849] FATAL:  role "root" does not exist
...
```

I'm reverting this PR for now to avoid confusing new users with these scary looking errors.

**Comment by ruslandoga** [comment]
Related to https://github.com/plausible/community-edition/issues/146, but it's unlikely to be the cause.

**Comment by willnode** [comment]
Hello, sorry this change bothering you. I should really checking it from ground zero.

Here's my exact setup I currently use. I use docker rootless setup though I'm skeptical it has any difference. Maybe the version difference could be the cause?

```
  plausible_db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready
      start_interval: 2s
      start_period: 1m
```

**Comment by BtbN** [comment]
This should be pretty easy to fix by just adding `-U postgres` to the pg_isready invocation.

**Pull request merged**
