### PR TITLE
Add DATABASE_SOCKET_DIR and related to README.md

### PR DESCRIPTION
**Pull request by titanofold**
Support for connecting to PostgreSQL via Unix domain socket was added a couple of years ago, and this should help advertise that support.

There are 3 additional influential variables that users should expect to need defining:
- DATABASE_NAME
- PGUSER
- PGPASSWORD

While DATABASE_NAME is Plausible-specific, PGUSER and PGPASSWORD support comes from the underlying database driver. Rather than making users dig through code and commit history for this info (because the driver doesn't document this either), we include it here for ease of access.

### CODE REVIEW

**Comment by ruslandoga** [comment]
👋 @titanofold 

PG env vars are confusing. Even if [Postgrex](https://github.com/elixir-ecto/postgrex) supports them, Plausible should have its own, like `DATABASE_USERNAME` and `DATABASE_PASSWORD`.

**Comment by ruslandoga** [comment]
> **Cannot** be used to connect to Unix domain socket. See [DATABASE_SOCKET_DIR](#database_socket_dir).

This makes me thing we should be able to support Unix domain sockets via DATABASE_URL. We can parse it in the config and if it's `unix://` we treat it as `unix://<username>:<password>@<socket_dir>/<database>`

Does it make sense? If so, we can open a PR into Plausible with this change.

**Comment by titanofold** [comment]
> 👋 @titanofold
> 
> PG env vars are confusing. Even if [Postgrex](https://github.com/elixir-ecto/postgrex) supports them, Plausible should have its own, like `DATABASE_USERNAME` and `DATABASE_PASSWORD`.

I disagree about confusing. The [PG vars](https://www.postgresql.org/docs/current/libpq-envars.html) are standard across platforms/programs that use the PostgreSQL. So, they're somewhat expected. There's actually quite a few that Postgrex supports, as I discovered.

I agree that It is definitely not consistent. I don't know enough about the language Plausible is written in to add that support. But, this may not be needed in the first place.

> > **Cannot** be used to connect to Unix domain socket. See [DATABASE_SOCKET_DIR](#database_socket_dir).
> 
> This makes me thing we should be able to support Unix domain sockets via DATABASE_URL. We can parse it in the config and if it's `unix://` we treat it as `unix://<username>:<password>@<socket_dir>/<database>`
> 
> Does it make sense? If so, we can open a PR into Plausible with this change.

Not really. However, this prompted me to look into this more.

I'm using Docker image version 1.4.4 so I may be *way*, **way** behind.

I was going to say that both Plausible and Postgrex need to properly support the [standard connection strings](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING). It looks like Postgrex got some support in [June 2022](https://github.com/elixir-ecto/postgrex/commit/f2d73e3267cf3f10ecfa72cfe68caeb7d51349f9), which would not have been included with 1.4.4 because 1.4.4 was released 6 months before.

The full spec says the socket dir can be given in the hostname (`postgresql://...:...@%2Frun%2Fpostgresql/plausible_db`) or query host param (`postgresql:///plausible_db?host=/run/postgresql`). From what I can see, only the former is supported. That's good enough. Supporting the latter would be nice just to keep from suprising people.

From what I can see on the connection history, Plausible has been patched to work with Postgrex's incomplete connstring support. I don't know if Plausible's DATABASE_URL interacts properly with Postgrex's socket support.

I'm going to be upgrading to 2.1.0 soon, but I was running into space/memory/processing constraints on my tiny host, which prompted my delving into this problem and my making what may be now an outdated contribution. I'll follow up when I get that far.

There's a contribution here that may still be worthwhile as to note the outdated troubles, but not to dedicate so much space to the matter.

**Comment by ruslandoga** [comment]
> From what I can see, only the former is supported. That's good enough. Supporting the latter would be nice just to keep from suprising people.

I don't think it is, at least judging by the PR you linked.

I think we'd need to decode DATABASE_URL ourselves and supply the parsed out options to Postgrex. It would replace [this block](https://github.com/plausible/analytics/blob/823f7a88002f6983ca2de030b0fa19454c55554b/config/runtime.exs#L326-L341) with something like this:

```elixir
%URI{host: db_host} = db_uri = URI.parse(db_url)
db_socket_dir? = String.start_with?(db_host, "%2F") or db_host == ""

if db_socket_dir? do
  [database] = String.split(db_uri.path, "/", trim: true)
  
  socket_dir =
    if host == "" do
      db_uri.query |> URI.decode_query() |> Map.fetch!("host")
    else
      URI.decode_www_form(db_host)
    end
  
  config :plausible, Plausible.Repo,
    socket_dir: socket_dir,
    database: database
    
  if username = db_uri.userinfo do
    [username, password] = String.split(userinfo, ":")
    
    config :plausible, Plausible.Repo,
      username: username,
      password: password
  end
else
  config :plausible, Plausible.Repo,
    url: db_url,
    socket_options: maybe_ipv6,
    ssl_opts: [
      cacertfile: db_cacertfile,
      verify: :verify_peer,
      customize_hostname_check: [
        match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
      ]
    ]
end
```

**Comment by ruslandoga** [comment]
PR: https://github.com/plausible/analytics/pull/4202

**Comment by ruslandoga** [comment]
Closing as https://github.com/plausible/analytics/pull/4202 has been merged and the next release would allow configuring socket dir via DATABASE_URL.

---

@titanofold thank you for reporting the issue and providing the information on the URL scheme!

**Pull request closed without merging**
